### ISSUE TITLE
Request list should schrink on smaller screens

### ISSUE THREAD

**Issue by pietrzakkuba** [kffl/triss-client#13]
## Description

Request list's width should be dynamically determined by window's size

## Acceptance criteria

- [x] First one
- [x] The other one

**Comment by Rybov** [comment]
Requests list didn't schrinkg because of constant filter box sizes. Now we have filters above grid and everything works perfectly ~ Marceli Jerzyński

**Comment by pietrzakkuba** [comment]
Great work Marceli!
