### ISSUE TITLE
New request form

### ISSUE THREAD

**Issue by kffl** [kffl/triss-client#3]
### Related backend issue: 

kffl/triss-server#4

## Description

Employee (Prelegent) user should be able to create a new request that then will be processed by: Director, Wilda and Rector by filling in an appropriate form in the client app.

## Acceptance criteria

- [x] The form inside the app should contain the same information as the paper-based one
- [x] The request form should have appropriate validation

**Comment by pietrzakkuba** [comment]
branch: https://github.com/kffl/triss-client/tree/feature/new-request-form
